name: Set up JDK 17
runs-on: ubuntu-latest
steps:
  - name: Set up JDK 17
    uses: actions/setup-java@v3
    with:
      distribution: 'temurin'
      java-version: '17'
      check-latest: false
      cache: gradle
  - name: Print Java Version
    run: javac -version
