name: Run And Generate Test Report Artifact
runs-on: ubuntu-latest
needs: change_wrapper_permissions_job
steps:
  - name: Checkout
    uses: actions/checkout@v3
  - name: Run Debug Test
    run: ./gradlew testDebugUnitTest --continue
  - name: Upload Test Reports
    if: ${{ always() }}
    uses: actions/upload-artifact@v3
    with:
      name: test-reports
      path: '**/build/reports/tests/'
