name: build-and-test
on:
  pull_request:
    branches:
      - master
      - dev
    tags:
      - 'v*'
jobs:
  local_test_job:
    name: running-local-unit-tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
      - name: Print Java Version
        run: javac -version
      - name: Change Wrapper Permissions
        run: chmod +x ./gradlew
      - name: Run Debug Test
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/build/reports/tests/'


