name: Build And Test Workflow
on:
  pull_request:
    branches: [ "master","dev" ]

jobs:
  base_setup_job:
    name: init base setup
    uses: ./init_workflow.yml
  test_report_artifact_job:
    name: run local unit test cases and export the test report
    uses: ./test_report_workflow.yml
    needs: base_setup_job
  build_project_job:
    name: build the project
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - base_setup_job
      - test_report_artifact_job




