name: Development Build And Test Workflow
on:
  pull_request:
    branches: [ "dev" ]

jobs:
  checkout_job:
    uses: ./.github/workflows/jobs/checkout.yml

  setup_java_job:
    uses: ./.github/workflows/jobs/setup_java.yml
    needs: checkout_job

  change_wrapper_permissions_job:
    uses: ./.github/workflows/jobs/change_wrapper_permissions.yml
    needs: setup_java_job

  run_debug_test_job:
    uses: ./.github/workflows/jobs/run_debug_test.yml
    needs: change_wrapper_permissions_job

  build_with_gradle_job:
    uses: ./.github/workflows/jobs/build_with_gradle.yml
    needs: run_debug_test_job
