name: Build And Test Workflow
on:
  pull_request:
    branches: [ "master","dev" ]

jobs:
  base_setup_job:
    name: init base setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false
          cache: gradle
      - name: Print Java Version
        run: javac -version

  test_report_artifact_job:
    name: run local unit test cases and export the test report
    runs-on: ubuntu-latest
    needs: base_setup_job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Change Wrapper Permissions
        run: chmod +x gradlew
      - name: Run Debug Test
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/build/reports/tests/'

  build_project_job:
    name: build the project
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle
        run: ./gradlew build
    needs:
      - base_setup_job
      - test_report_artifact_job