name: Build And Test Workflow
on:
  pull_request:
    branches: [ "master","dev" ]

jobs:
  base_setup_job:
    name: init base setup
    uses: ./.github/workflows/init_workflow.yml@dev

  test_report_artifact_job:
    name: run local unit test cases and export the test report
    uses: ./.github/workflows/test_report_workflow.yml@dev
    needs: base_setup_job

  build_project_job:
    name: build the project
    runs-on: ubuntu-latest
    steps:
      - name: Build with Gradle
        run: ./gradlew build
    needs:
      - base_setup_job
      - test_report_artifact_job