name: run tests and upload test report
on:
  workflow_call:

jobs:
  run_unit_test_job:
    name: running local unit tests
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Change Wrapper Permissions
        run: chmod +x gradlew
      - name: Run Debug Test
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/build/reports/tests/'
